config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
                     sessions: 'users/sessions',
                     registrations: 'users/registrations',
                     confirmations: 'users/confirmations',
                     passwords: 'users/passwords',
                     unlocks: 'users/unlocks',
                     omniauth_callbacks: 'users/omniauth_callbacks'
                   }

  # Subdomains are currently not available on heroku
  #constraints(subdomain: /.+/) do
    #get '/:url', to: 'frontend/case_studies#show', by_domain: true
    #get '*path' => redirect('/')
  #end

  # For redirect after sign in
  get 'case_studies' => 'backend/case_studies#index', as: :user_root

  concern :publishable do
    post :publish, on: :member
  end

  concern :approvable do
    post :approve, on: :member
  end

  resources :case_studies, controller: 'backend/case_studies',
            path_names: { edit: 'edit(/:step)' },
            concerns: :publishable do
    #collection do
    #  post :add_image, :add_template
    #end
  end

  resources :testimonials, controller: 'backend/testimonials',
            :concerns => [:publishable, :approvable]

  resources :reviews, controller: 'backend/reviews',
            :concerns => [:publishable, :approvable]

  resources :requests, controller: 'backend/requests', :only => [:index, :destroy]

  match '/requests/new_testimonial' => 'backend/requests#new_testimonial',
    :via => :get, :as => :new_testimonial_request
  match '/requests/create_testimonial' => 'backend/requests#create_testimonial',
    :via => :post, :as => :create_testimonial_request

  match '/requests/new_review' => 'backend/requests#new_review',
    :via => :get, :as => :new_review_request
  match '/requests/create_review' => 'backend/requests#create_review',
    :via => :post, :as => :create_review_request

  match '/testimonial/request/new/:token' => 'backend/requests#new_customer_testimonial',
    :via => :get, :as => :new_customer_testimonial
  match '/testimonial/request/:token' => 'backend/requests#create_customer_testimonial',
    :via => :post, :as => :create_customer_testimonial

  match '/review/request/new/:token' => 'backend/requests#new_customer_review',
    :via => :get, :as => :new_customer_review
  match '/review/request/:token' => 'backend/requests#create_customer_review',
    :via => :post, :as => :create_customer_review

  resources :templates, controller: 'backend/templates'

  # embedding routes
  match '/render_tile/:id' => 'frontend/case_studies#tile', via: [:get, :options]
  match '/render_testimonial/:id' => 'frontend/case_studies#testimonial', via: [:get, :options]

  get ':user_url' => 'frontend/case_studies#index', as: :public_case_studies
  get ':user_url/code' => 'frontend/case_studies#code', as: :code_case_studies
  get ':user_url/:url' => 'frontend/case_studies#show', as: :public_case_study

  root 'backend/home#index'
end

app/controllers/backend/application_controller.rb
module Backend
  class ApplicationController < ::ApplicationController
    before_filter :authenticate_user!
  end
end

app/controllers/backend/case_studies_controller.rb
class Backend::CaseStudiesController < Backend::ApplicationController
  #include Wicked::Wizard
  before_action :set_case_study, except: [:index, :new, :create]
  #steps :template, :content, :tile_template, :tile_content

  def index
    @case_studies = current_user.case_studies.all
  end

  def new
    @case_study = CaseStudy.new
  end

  def main
    wizard_save(nil, next: :template, back: :edit)
  end

  # def logo
  #   binding.pry
  #   @case_study.update(case_study_params) if case_study_params
  #   wizard_save(:validate_logo, next: :template, back: :logo)
  # end

  def template
    if case_study_params[:template_id]
      @case_study.insert_template CaseStudyTemplate
                                      .find(case_study_params[:template_id]).template
    end
    wizard_save(:validate_template, next: :content, back: :template)
  end

  def content
    @case_study.update(case_study_params) if case_study_params
    #wizard_save(:validate_template, next: :tile_template, back: :content)
    @case_study.next_step
    @case_study.insert_tile TileTemplate.take.template # temp we have one tile template
    redirect_to case_study_path(@case_study), notice: 'Case study created!'
  end

  def tile_template
    # TBD
  end

  def tile_content
    # TBD
  end

  def create
    @case_study = current_user.case_studies.new(case_study_params)
    wizard_save(nil, next: :template, back: :new)
  end

  def show
    redirect_to case_studies_path, alert: 'Case study is not finished' unless @case_study.ready?
  end

  def edit
    params[:step] ||= @case_study.ready? ? :content : @case_study.step
    render params[:step]
  end

  def update
    send(params[:step]) if params[:step].present?
  end

  def destroy
    redirect_to case_studies_path, notice: 'Case study destroyed' if @case_study.destroy
  end

  #def add_template
  #  template = Nokogiri::HTML(params[:template].read)
  #  template.css('script,iframe').remove
  #  @template = template.to_s
  #  @editor_index =  %w(case_study tile).find_index(params[:type])
  #  respond_to :js
  #end

  def publish
    @case_study.toggle_published
    redirect_to case_studies_path,
                notice: "Case study was #{'un' unless @case_study.published? }published"
  end

  protected

  def set_case_study
    @case_study = CaseStudy.find(params[:id])
  end

  def case_study_params
    if params[:case_study].present? && params[:case_study].any?
      params.require(:case_study).permit(:image, :client, :title, :template_id,
                                         :template_content, :tile_template_content)
    end
  end

  def wizard_save(validation, args = {})
    if (validation ? send(validation, @case_study) : true) && @case_study.save
      @case_study.next_step
      redirect_to edit_case_study_path(@case_study, step: args[:next])
    else
      render args[:back]
    end
  end

  private

  def validate_logo(cs)
    cs.errors[:image] << 'should be uploaded' unless cs.image.present?
    cs.errors.empty?
  end

  def validate_template(cs)
    cs.errors[:template_content] << 'should be choosen' unless cs.template_content.present?
    cs.errors.empty?
  end

end

app/controllers/backend/home_controller.rb
class Backend::HomeController < ApplicationController
  def index
    # overview page
  end
end

app/controllers/backend/requests_controller.rb
class Backend::RequestsController < ApplicationController
  #has_scope :page, default: 1
  before_action :init_request, :only => [:new_testimonial, :new_review]



  def create_testimonial
    @request = current_user.requests.new(request_params)
    @request.request_type = :testimonial

    if @request.save
      @request.send_mail
      redirect_to requests_path, :notice => 'Request for Testimonial sent'
    else
      @testimonial = Testimonial.new
      @templates = TestimonialTemplate.all
      render 'backend/testimonials/new'
    end
  end

  def create_review
    @request = current_user.requests.new(request_params)
    @request.request_type = :review

    if @request.save
      @request.send_mail
      redirect_to requests_path, :notice => 'Request for Review sent'
    else
      @review = Review.new
      render 'backend/reviews/new'
    end
  end

  def index
    @index = eval params[:index] if params[:index]
    @requests = current_user.requests.order('created_at DESC')
  end

  def destroy
    @request = current_user.requests.find params[:id]
    redirect_to requests_path, notice: 'Request destroyed' if @request.destroy
  end

  def new_customer_testimonial
    @request = Request.find_by_token params[:token]
    if @request && @request.status == 'sent'
      @testimonial =
        Testimonial.new :name => @request.name, :request_token => params[:token]
      @templates = TestimonialTemplate.all
    else
      redirect_to testimonials_path, :notice => 'Testimonial created'
    end
  end

  def new_customer_review
    @request = Request.find_by_token params[:token]
    if @request && @request.status == 'sent'
      @review =
        Review.new :name => @request.name, :request_token => params[:token]
    else
      redirect_to reviews_path, :notice => 'Review created'
    end
  end

  def create_customer_testimonial
    @request = Request.find_by_token params[:token]
    @user = @request.user
    @testimonial = @user.testimonials.new(testimonial_params)

    if @testimonial.save
      # @request.testimonial = @testimonial
      @request.update_attributes :status => 'Filled by customer'
      redirect_to testimonials_path, :notice => 'Thank you for your feedback!' # later thanks page
    else
      @templates = TestimonialTemplate.all
      render :new_customer_testimonial
    end
  end

  def create_customer_review
    @request = Request.find_by_token params[:token]
    @user = @request.user
    @review = @user.reviews.new(review_params)

    if @review.save
      # @request.review = @review
      @request.update_attributes :status => 'Filled by customer'
      redirect_to reviews_path, :notice => 'Thank you for your feedback!' # later thanks page
    else
      render :new_customer_review
    end
  end

  private

  def init_request
    @request =
      Request.new :sender => current_user.name, :reply_to => current_user.email
  end

  def testimonial_params
    params.require(:testimonial).permit(:image, :name, :role, :company, :content, :template_id)
  end

  def review_params
    params.require(:review).permit(:image, :name, :role, :company, :content, :title, :rating)
  end

  def request_params
    params.require(:request).
      permit(:name, :email, :sender, :reply_to, :subject, :message)
  end

end

app/controllers/backend/reviews_controller.rb
class Backend::ReviewsController < ApplicationController
  before_action :set_review, except: [:index, :new, :create]

  def index
    @reviews = current_user.reviews.order('created_at DESC')
  end

  def new
    @review = Review.new
    @request =
      Request.new :sender => current_user.name, :reply_to => current_user.email
  end

  def create
    @review = current_user.reviews.new(review_params)

    if @review.save
      redirect_to reviews_path, :notice => 'Review created'
    else
      @request =
        Request.new :sender => current_user.name, :reply_to => current_user.email
      render :new
    end
  end

  def edit
    @review = Review.find params[:id]
  end

  def update
    if @review.update(review_params)
      redirect_to reviews_path, :notice => 'Review updated'
    else
      render :edit
    end
  end

  def destroy
    if @review.destroy
      redirect_to reviews_path, :notice => 'Review destroyed'
    end
  end

  # def publish
  #   @testimonial.toggle(:published).save
  #   if @testimonial.testimonial_request && @testimonial.published?
  #     @testimonial.testimonial_request.destroy
  #   end
  #   redirect_to testimonials_path,
  #               notice: "Testimonial was #{'un' unless @testimonial.published? }published"
  # end

  def approve
    @review.update_attributes :approved => true

    redirect_to reviews_path, :notice => "Review was approved"
  end

  protected

  def set_review
    @review = current_user.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:image, :name, :role, :company, :content, :title, :rating)
  end
end

app/controllers/backend/templates_controller.rb
class Backend::TemplatesController < Backend::ApplicationController
  #inherit_resources
  #actions :show
  #respond_to :json
end

app/controllers/backend/testimonials_controller.rb
class Backend::TestimonialsController < ApplicationController
  before_action :set_testimonial, except: [:index, :new, :create]

  def index
    @testimonials = current_user.testimonials.order('created_at DESC')
  end

  def new
    @testimonial = Testimonial.new
    @templates = TestimonialTemplate.all
    @request =
      Request.new :sender => current_user.name, :reply_to => current_user.email
  end

  def create
    @testimonial = current_user.testimonials.new(testimonial_params)

    if @testimonial.save
      redirect_to testimonials_path, notice: 'Testimonial created'
    else
      @templates = TestimonialTemplate.all
      @request =
        Request.new :sender => current_user.name, :reply_to => current_user.email
      render :new
    end
  end

  def edit
    @testimonial = Testimonial.find params[:id]
    @templates = TestimonialTemplate.all
  end

  def update
    if @testimonial.update(testimonial_params)
      redirect_to testimonials_path, notice: 'Testimonial updated'
    else
      render :edit
    end
  end

  def destroy
    redirect_to testimonials_path, notice: 'Testimonial destroyed' if @testimonial.destroy
  end

  def publish
    @testimonial.toggle(:published).save
    if @testimonial.testimonial_request && @testimonial.published?
      @testimonial.testimonial_request.destroy
    end
    redirect_to testimonials_path,
                notice: "Testimonial was #{'un' unless @testimonial.published? }published"
  end

  def approve
    @testimonial.update_attributes :approved => true

    redirect_to testimonials_path, :notice => "Testimonial was approved"
  end

  protected

  def set_testimonial
    @testimonial = current_user.testimonials.find(params[:id])
  end

  def testimonial_params
    params.require(:testimonial).permit(:image, :name, :role, :company, :content, :template_id)
  end
end

app/views/backend/testimonials_bak/_form.html.slim
.row
  .col-xs-12
    #accordion.panel-group
      .panel.panel-default
        .panel-heading
          h4.panel-title
            a data-parent="#accordion" data-toggle="collapse" href="#testimonialInfo" = 'Main info'
        #testimonialInfo.panel-collapse.collapse.in
          .panel-body
            .row
              = f.input :name, placeholder: t('activerecord.attributes.testimonial.name')
              = f.input :role, placeholder: t('activerecord.attributes.testimonial.role')
              = f.input :company, placeholder: t('activerecord.attributes.testimonial.company')
              = f.input :content, placeholder: t('activerecord.attributes.testimonial.content')
              = f.input :image, wrapper: :horizontal_file_input, label_html: {class: 'col-md-2'},
                        hint: t('.image_hint'), required: false
            .clearfix
              a.btn.btn-primary.btn-block#infoNext(
                data-parent="#accordion"
                data-toggle="collapse"
                href="#testimonialTemplate")
                | Next
            //.reset-info = t('.reset')
      .panel.panel-default
        .panel-heading
          h4.panel-title
            a.collapsed data-parent="#accordion" data-toggle="collapse" href="#testimonialTemplate" = t('.testimonial_template')
        #testimonialTemplate.panel-collapse.collapse
          .panel-body
            .row
              - TestimonialTemplate.all.each do |t|
                /= t.type
                = render 'backend/testimonials/template_preview', t: t
            .clearfix
            /.reset-info = t('.reset')

app/views/backend/testimonials_bak/_list_testimonial.html.slim
.col-xs-3.case-study
  = link_to testimonial_path(resource) do
    .content
      h2 = resource.name
      /case_study_path(_resource)
      h2 = resource.company
  .controls
    - if resource.published?
      .btn.btn-success.btn-sm
        = link_to 'Published', publish_testimonial_path(resource),
                  data: { confirm: 'Are you sure you want make this testimonial draft?' }
    - else
      .btn.btn-danger.btn-sm
        = link_to 'Draft', publish_testimonial_path(resource),
                  data: { confirm: 'Are you sure you want publish this testimonial?' }
    .buttons-sm.dropdown
      button.btn.btn-default.btn-sm.dropdown-toggle data-toggle="dropdown"
        = t('views.common.actions')
        |&nbsp;
        = fa_icon 'caret-down'
      ul.dropdown-menu
        /li = link_to t('views.common.preview'), public_case_study_path(resource.user.url, resource.url)
        li = link_to t('views.common.edit'), edit_testimonial_path(resource)
        li = link_to t('views.common.delete'), testimonial_path(resource), method: :delete

app/views/backend/testimonials_bak/_template_preview.html.slim
.col-xs-12.col-sm-6.col-md-4
  .thumbnail
    = image_tag t.preview.url
    .caption
      h3.text-center = t.title
      p = t.description
      /a.btn.btn-primary.btn-block.choose-template(
          href="#{target}"
          data-toggle="collapse"
          data-parent="#accordion"
          data-target="#{target}"
          data-editor="#{editor}"
          data-url="#{template_path(t.id, :json)}")
        = t('.choose')

app/views/backend/testimonials_bak/edit.html.slim
.container.backend-edit-case-study
  = simple_form_for resource, wrapper: :horizontal_form_without_labels,
                    html: { class: 'form-horizontal case-study-form' } do |f|
    .row
      .col-xs-12.header
        .buttons
          = f.submit t('views.common.save'), class: 'btn btn-primary'
        h1.page-header = I18n.t('views.common.edit_object', obj: 'testimonial')

    = render 'form', f: f

app/views/backend/testimonials_bak/index.html.slim
.container.backend-case-studies
  .row
    .col-xs-12.header
      .buttons
        = link_to t('.new_button'), new_testimonial_path, class: 'btn btn-primary'
      h1.page-header = t('.title')

  .row.backend-list-case-study
    - collection.each do |resource|
      = render 'list_testimonial', resource: resource

  .text-center = paginate collection

app/views/backend/testimonials_bak/new.html.slim
.container.backend-new-case-study
  = simple_form_for resource, wrapper: :horizontal_form_without_labels,
                    html: { class: 'form-horizontal case-study-form' } do |f|
    .row
      .col-xs-12.header
        .buttons
          = f.submit t('views.common.save'), class: 'btn btn-primary'
        h1.page-header = I18n.t('views.common.new_object', obj: 'testimonial')

    = render 'form', f: f

app/views/backend/testimonials_bak/show.html.slim
.container.backend-case-study
  .row
    .col-xs-12.header
      .buttons
        = link_to t('views.common.edit'), edit_testimonial_path(resource), class: 'btn btn-primary'
      h1.page-header Testimonial

  .row
    .col-xs-6
      .row
        h2
          | Testimonial preview
        .tile-preview
          == resource.template_with_pic
    .col-xs-6
      .row
        h2
          | Testimonial code
        .tile-code
          = text_area_tag :tile_code, resource.code(request.base_url)
          = link_to 'Copy to clipboard', '#', class: 'btn btn-primary', id: 'tileToClipboard'